pipeline:
  name: "Build Scan and Deploy "
  identifier: Build_Scan_and_Deploy
  template:
    templateRef: account.Build_Scan_and_Deploy
    versionLabel: 1.0.0
    gitBranch: master
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: <+input>
            repoName: <+input>
            build: <+input>
      stages:
        - stage:
            identifier: Build_Image
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>
              execution:
                steps:
                  - step:
                      identifier: Build_Image
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
        - stage:
            identifier: Deploy_to_Test
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
        - stage:
            identifier: Deploy_to_Prod
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
      variables:
        - name: docker_image
          type: String
          value: <+input>.default(The image name where the image being built will be pushed to)
        - name: docker_tag
          type: String
          value: <+input>.default(harness-<+codebase.commitSha>)
  tags: {}
  projectIdentifier: Spring_Forward
  orgIdentifier: default
