pipeline:
  name: "Build Scan and Deploy "
  identifier: Build_Scan_and_Deploy
  tags: {}
  template:
    templateRef: account.Build_Scan_and_Deploy
    versionLabel: v2
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: <+input>
            repoName: <+input>
            build: <+input>
      stages:
        - stage:
            identifier: Build_Image
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>
              execution:
                steps:
                  - step:
                      identifier: Build_Image
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
                  - parallel:
                      - insert:
                          identifier: Extra_Testing
                          steps: <+input>
        - stage:
            identifier: Deploy_to_Test
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
        - stage:
            identifier: Deploy_to_Prod
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              execution:
                steps:
                  - insert:
                      identifier: Approval
                      steps:
                        - step:
                            type: HarnessApproval
                            name: HarnessApproval_1
                            identifier: HarnessApproval_1
                            spec:
                              approvalMessage: Please review the following information and approve the pipeline progression
                              includePipelineExecutionHistory: true
                              isAutoRejectEnabled: false
                              approvers:
                                userGroups:
                                  - account._account_all_users
                                minimumCount: 1
                                disallowPipelineExecutor: false
                              approverInputs: []
                            timeout: 1d
      variables:
        - name: docker_image
          type: String
          value: <+input>.default(The image name where the image being built will be pushed to)
        - name: docker_tag
          type: String
          value: <+input>.default(harness-<+codebase.commitSha>)
  projectIdentifier: Spring_Forward
  orgIdentifier: default
