pipeline:
  name: Build and Deploy PR
  identifier: Build_and_Deploy_PR
  template:
    templateRef: account.Build_and_Deploy_PR
    versionLabel: 1.0.0
    gitBranch: master
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: <+input>
            repoName: <+input>
            build: <+input>
      stages:
        - stage:
            identifier: Build_Image
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: Build_Image
                      type: BuildAndPushDockerRegistry
                      spec:
                        repo: <+input>
        - stage:
            identifier: Deploy_Image
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
  tags: {}
  projectIdentifier: Spring_Forward
  orgIdentifier: default
